### ISSUE TITLE
Unable to play Spotify playlist from my own library

### ISSUE THREAD

**Issue by Jaelabi** [robinfriedli/botify#139]
Hello!

Even after logging in to my own Spotify account with botify, it still doesn't connect to my own playlists.

I tried using the command **$botify play $spotify $list $own massive tb playlist wow**, but it didn't work.  I am able to use the command **$botify play $spotify $list throwback jams** to play random Spotify playlists, but I am unable to access my own library when I do that - I only wanted to try this command just in case.

This is what I keep getting in response whenever I try to play my own playlist:
> Exception
> NullPointerException: null
>CommandContext ID
> 65520798-94e1-40c3-aad6-a8e68f7e1808 (but the ID changes each time)

I am able to play the same playlist though if I use the URL **$botify play someurl.com**, so playing my own playlists work that way (but I'd have to keep going to the browser version of Spotify to grab a playlist url every time I want to change it).  It also doesn't let me play the generic playlist of "Liked Songs" since that doesn't have a URL (https://open.spotify.com/collection/tracks) that botify recognizes.

**Comment by robinfriedli** [comment]
I presume you're hosting your own instance of the bot? Try restarting the bot, this is a known issue with the Spotify API. I'll see if updating the dependency to the latest version below 6.0 helps (since that is a massively breaking change this update was done for botify 2 -> the development/v2.0 branch and won't be patched down to botify 1). It seems that there is an issue with the `GetListOfCurrentUsersPlaylistsRequest` class where the returned json string is null thus parsing fails
```
net.robinfriedli.botify.exceptions.CommandRuntimeException: java.lang.NullPointerException
	at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:125) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.CommandInterceptorChain.intercept(CommandInterceptorChain.java:69) ~[classes/:?]
	at net.robinfriedli.botify.command.CommandManager.lambda$runCommand$0(CommandManager.java:54) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	at net.robinfriedli.botify.concurrent.QueuedThread.run(QueuedThread.java:18) ~[classes/:?]
	at net.robinfriedli.botify.concurrent.CommandExecutionThread.run(CommandExecutionThread.java:23) ~[classes/:?]
Caused by: java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[gson-2.8.5.jar:?]
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:149) ~[spotify-web-api-java-4.1.0.jar:?]
	at com.wrapper.spotify.requests.data.playlists.GetListOfCurrentUsersPlaylistsRequest.execute(GetListOfCurrentUsersPlaylistsRequest.java:37) ~[spotify-web-api-java-4.1.0.jar:?]
	at net.robinfriedli.botify.audio.spotify.SpotifyService.searchOwnPlaylist(SpotifyService.java:92) ~[classes/:?]
	at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.lambda$loadSpotifyList$2(AbstractPlayableLoadingCommand.java:160) ~[classes/:?]
	at net.robinfriedli.botify.function.modes.SpotifyUserAuthorizationMode.lambda$wrap$0(SpotifyUserAuthorizationMode.java:27) ~[classes/:?]
	at net.robinfriedli.jxp.exec.BaseInvoker.invoke(BaseInvoker.java:22) ~[JXP-2.0.jar:?]
	at net.robinfriedli.botify.function.SpotifyInvoker.invoke(SpotifyInvoker.java:47) ~[classes/:?]
	at net.robinfriedli.botify.function.SpotifyInvoker.invoke(SpotifyInvoker.java:51) ~[classes/:?]
	at net.robinfriedli.botify.command.AbstractCommand.runWithLogin(AbstractCommand.java:198) ~[classes/:?]
	at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.loadSpotifyList(AbstractPlayableLoadingCommand.java:182) ~[classes/:?]
	at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.doRun(AbstractPlayableLoadingCommand.java:71) ~[classes/:?]
	at net.robinfriedli.botify.command.commands.PlayCommand.doRun(PlayCommand.java:44) ~[classes/:?]
	at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:51) ~[classes/:?]
	... 10 more
```

> (but the ID changes each time)

Well it's a different command execution each time, isn't it. The command context id can be used to find matching log entries and the corresponding database entry in the command_history table.

> (but I'd have to keep going to the browser version of Spotify to grab a playlist url every time I want to change it)

No, you don't. You can just right click the playlist in your Spotify client or click the 3 dots then click on 'Share' and then copy the playlist link or Spotify URI.

>  It also doesn't let me play the generic playlist of "Liked Songs" since that doesn't have a URL

You can't play that either way as it is not a playlist.

**Comment by robinfriedli** [comment]
Seeing as command 65520798-94e1-40c3-aad6-a8e68f7e1808 was executed on the public instance and matches your description you aren't hosting your own instance. In that case I've already restarted the bot and it should be working again.

**Comment by Jaelabi** [comment]
Thanks for restarting the bot - it works now.
