### ISSUE TITLE
Execution failed for task ':bootRun'.

### ISSUE THREAD

**Issue by 3DSBricker** [robinfriedli/botify#173]
Hi,
I'm getting some issues when trying to run Botify. When I try to run it with either Gradlew or Gradle, I'm getting the error that bootRun doesn't excist. Here is the error:
PS C:\Botify> ./gradlew bootRun                                                                                                                                                     
> Task :bootRun FAILED

              .~mw,.
           . 7NNNNNNNNm      gNNNNNm,                                                                     ..          ,,,,
           NNNm,"""7NNNNb   NNNNNNNN".w             #NNN                                      .,,,       NNNN      .NNNNNNE
           NNNNNb   /NNNNb  ANNNb   NNNN            #NNN                                      (NNN       "NM"      NNNE
            7NNNNNNNNNNNNE   7NNNNN#NNNN            #NNN   .,,,.              .,,,,.          #NNN                jNNNC
              7NNNNNNNNN"  (N  "NNNNNNNE            #NNN,#NNNNNNNNm       .#NNNNNNNNNNm    (NNNNNNNNNL   NNNN   NNNNNNNNNN   NNNb       (NNN
                          dNNNNw                    #NNNN"`   '7NNNN,    #NNNM"    "NNNNb     (NNN       NNNN     jNNNC      NNNb       (NNN
                        `"NNNNNNM" .,,.             #NNN         NNNN   #NNNC        (NNNb    (NNN       NNNN     jNNNC      NNNb       (NNN
               .#NNNNNNNNm  "NN  #NNNNNNNW,         #NNN         (NNN   NNNN          NNNN    (NNN       NNNN     jNNNC      NNNb       (NNN
              #NNNNNNNNNNNNN  7 #NNNNNNNNNNN        #NNN         #NNN   #NNN         .NNNE    (NNN       NNNN     jNNNC      NNNb       (NNN
             #NNNNNN" "NNNNNN   #NNNN-   NNNN       #NNNw       #NNNE    #NNN,      ,NNNN     (NNN       NNNN     jNNNC      NNNN,    .gNNNN
             #NNNNN,    NNNNNb   NNNNNw.. 7NNL      #NNNNNNNNNNNNNN'      7NNNNNNNNNNNNC      `NNNNNNN   NNNN     jNNNC      ?NNNNNNNNNM7NNN
              NNNNE ,mm#NNNNNL    7NNNNNNNNw``      *===  "7MNNM"`           "7MNRM="           7MNNM"   ====      ===         '7""""   (NNN
               NM .#NNNNNNNNN       "NNNNNNN"                                                                                 w        .NNNN
                 ^NNNNNNNNM"                                                                                                 NNNNN###NNNNN"
                                                                                                                               "*MNNMM=7

:: Spring Boot ::   v2.2.1.RELEASE
INFO  2020-10-30 16:57:39,222 [main] org.springframework.boot.StartupInfoLogger: Starting SpringBootstrap on Matthijs-PC with PID 4344 (C:\Botify\build\classes\java\main started by boeke in C:\Botify)
INFO  2020-10-30 16:57:39,225 [main] org.springframework.boot.SpringApplication: No active profile set, falling back to default profiles: default
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.<init>(GroovyBeanDefinitionReader.java:150)
        at org.springframework.boot.BeanDefinitionLoader.<init>(BeanDefinitionLoader.java:85)
        at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java:738)
        at org.springframework.boot.SpringApplication.load(SpringApplication.java:681)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at net.robinfriedli.botify.boot.SpringBootstrap.main(SpringBootstrap.java:26)
WARN  2020-10-30 16:57:39,310 [background-preinit] org.springframework.core.log.CompositeLog: For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
ERROR 2020-10-30 16:57:39,323 [main] org.springframework.boot.SpringApplication: Application run failed
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
        at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:258)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:111)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.<init>(GroovyBeanDefinitionReader.java:150)
        at org.springframework.boot.BeanDefinitionLoader.<init>(BeanDefinitionLoader.java:85)
        at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java:738)
        at org.springframework.boot.SpringApplication.load(SpringApplication.java:681)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at net.robinfriedli.botify.boot.SpringBootstrap.main(SpringBootstrap.java:26)
ERROR 2020-10-30 16:57:39,324 [main] net.robinfriedli.botify.boot.SpringBootstrap: Exception starting SpringApplication, AppContext could not be created.
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
        at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:258)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:111)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.<init>(GroovyBeanDefinitionReader.java:150)
        at org.springframework.boot.BeanDefinitionLoader.<init>(BeanDefinitionLoader.java:85)
        at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java:738)
        at org.springframework.boot.SpringApplication.load(SpringApplication.java:681)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at net.robinfriedli.botify.boot.SpringBootstrap.main(SpringBootstrap.java:26)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command 'C:\Program Files\Java\jdk-15.0.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by robinfriedli** [comment]
> java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

That's the issue. Have you run a gradle build? What happens when you run the jar in `build/libs/`-> `java -jar build/libs/botify-1.0-SNAPSHOT.jar`?

**Comment by 3DSBricker** [comment]
I did run gradle build and tried the java command but fails with the same error.
`java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache`

**Comment by robinfriedli** [comment]
Make sure your branch is up to date, run `gradle clean` and then `gradle build` again. If it still doesn't work try using jdk 11.

**Comment by 3DSBricker** [comment]
Thanks! JDK 11 did it. I'm now stuck at that I need a Top.gg token which I don't have because if I add the bot, they want to investigate by human first. Is there a way without that token?

**Comment by robinfriedli** [comment]
Yeah you can just leave that empty.

**Comment by 3DSBricker** [comment]
Well I'm getting th error that it can't resolve the placeholder of the top.gg token.

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[1;31mERROR[0;39m 2020-10-30 22:25:48,380 [[34mmain[0;39m] [33morg.springframework.boot.SpringApplication[0;39m: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'topGGComponent': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'botify.tokens.topgg_token' in value "${botify.tokens.topgg_token}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:403)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1429)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at net.robinfriedli.botify.boot.SpringBootstrap.main(SpringBootstrap.java:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'botify.tokens.topgg_token' in value "${botify.tokens.topgg_token}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:908)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1228)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:636)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:397)
        ... 25 common frames omitted

**Comment by 3DSBricker** [comment]
Did a little research. Apparently it doesn't see the application.properties. I found out how to do it with Maven by editing the pom.xml but don't know how to do it with Graddle.

**Comment by 3DSBricker** [comment]
Did a test. It does see the application.properties but really wants to see a IPv6 or Top.gg token. Both I don't have because I only have a IPv4. I do have a Local-link IPv6 but that didn't work.

**Comment by robinfriedli** [comment]
Don't remove the property, just leave the value empty.

**Comment by robinfriedli** [comment]
Also these properties are not in application.properties but settings-private.properties, just leave them how they are in the readme
```
##############################
# top.gg settings (optional) #
##############################
#copy your discord client id here
botify.tokens.discord_bot_id=
#copy your top.gg token here
botify.tokens.topgg_token=
```

**Comment by 3DSBricker** [comment]
I left them empty but still gives error. Slightly different one but it's now that the value of IPv6 is incorrect.

**Comment by robinfriedli** [comment]
```
########
# IPv6 #
########
botify.preferences.ipv6_blocks=
##############################
# top.gg settings (optional) #
##############################
#copy your discord client id here
botify.tokens.discord_bot_id=
#copy your top.gg token here
botify.tokens.topgg_token=
```

leaving them empty like that should definitely work, that's how I always run it locally.

**Comment by robinfriedli** [comment]
> I left them empty but still gives error.
Could you copy the error? Or is it still the same from the previous comment.

**Comment by 3DSBricker** [comment]
He is working. Thanks for the help. Now he's started, I have a other problem. When I want to play music, it won't respond in Discord but it does give an error in the console log: Unable to find net.robinfriedli.botify.entities.GuildSpecification with id 9. Btw, I fixed it by emptying the Discord client ID. I had filled in that and probably it thought I was using top.gg. Left them empty and it worked.

**Comment by robinfriedli** [comment]
That error probably just means the bot received a message while setting up the guild and has already associated the GuildSpecification with the GuildContext but the transaction has not been completed yet. It is unlikely that you entered the command so quickly, this usually only happens with very busy guilds where the bot receives a lot of messages instantly when joining. Try running a command again and see if the error gets thrown again.

**Comment by 3DSBricker** [comment]
It's with all commands each time. Even when I restart it or wait some time. Btw, can I disable or shorten the welcome message somewhere?

**Comment by robinfriedli** [comment]
Getting started message is in `botify/src/main/resources/xml-contributions/embedDocuments.xml`.

Can you attach a full log of starting the bot and trying to execute a command?

**Comment by 3DSBricker** [comment]
I had some issues with code snippet. I uploaded it to pastebin.
https://pastebin.com/rhetA71u

**Comment by robinfriedli** [comment]
Yup, the  error `EntityNotFoundException: Unable to find net.robinfriedli.botify.entities.GuildSpecification with id 4` is simply a symptom of the earlier error `ERROR: character with byte sequence 0xd0 0xaf in encoding "UTF8" has no equivalent in encoding "WIN1252"`. The database failed to persist the GuildSpecification entity, which then causes an error when executing a command because the GuildSpecification cannot be found. Your database is using the wrong encoding. Check what encoding you are using with `SHOW server_encoding;` (WIN1252 apparently) and try changing it to utf-8 with `SET CLIENT_ENCODING TO 'utf8';`.

The errors `IllegalStateException: No results found.` occur because I presume you deleted the getting-started message from embedDocuments.xml. I`ll push a fix that simply ignores that and just doesn't send the message instead.

**Comment by robinfriedli** [comment]
Also note the bot being unable to persist GuildSpecification entities is also why the bot sends a getting-started message each startup, which is why I presume you wanted to delete that message. Normally this only happens once per guild: when initializing a new guild that does not have a GuildSpecification yet.

**Comment by 3DSBricker** [comment]
Thank you so much! I don't know exactly what I did, I did reset and clean up the databases (just deleted them) and made new ones. (botify and botify2) Encode in UTF8, I thought it needed to be in WIN1252 as PGAdmin said it. I selected the template0 and it just worked. Tried the play command, and there he was! Playing my music.

**Comment by robinfriedli** [comment]
Nice. Glad to hear it's working now.
